### ISSUE TITLE
motion curve images not showing the actual animation curve

### ISSUE THREAD

**Issue by designakt** [bwinton/DesignSystem#66]
Comparing the image we show in [DS-Motion](https://bwinton.github.io/DesignSystem/motion-principles.html#animation-curve) with the image constructed on [cubic-bezier.com](http://cubic-bezier.com/#.07,.95,0,1) I see 2 different animation curves.
![ds-motion-curve](https://cloud.githubusercontent.com/assets/8145891/25226456/4b6f97f2-25c5-11e7-861c-e589f7626380.PNG)
It might lead to confusions if the values we provide do not align with the illustration we show. (Until I went to cubic-bezier, I assumed we had a rather relaxed animation curve.)
Expected result: animation curve has the same curvature than on cubic-bezier.

_mentioning @brassy- as she worked on this._

**Comment by brassy-** [comment]
The first curve is showing a speed value while the second is showing value. So the two curve looks different because they are different, even if they are the same. I see how this can be confusing.

To be honest, I placed the visual (which come from to @epang and Amy presentation) to give some context to @TLHuang. For me, it's her call here to how to visualise the curve.

**Comment by aminalhazwani** [comment]
Will close this. @TLHuang can follow up to the motion PR.
