### ISSUE TITLE
indicate external links with an icon next to the link

### ISSUE THREAD

**Issue by designakt** [bwinton/DesignSystem#88]
For people to not lose their open instance of the Design System when clicking on an external resource, we should open external resources in a new tab by default. (target="_blank")

**Comment by aminalhazwani** [comment]
I don't know if we should do this. There's this [interesting study](https://dubroy.com/blog/my-chi2010-talk-a-study-of-tabbed-browsing/) by Patrick Dubroy and a [talk](https://dubroy.com/blog/my-talk-at-mozilla/) which outlines that power users tend to open links in new tab only if they want to. I would assume that most of our visitors will be power users therefore the `target="_blank"` may not be the most expected behavior. What do you think?

**Comment by designakt** [comment]
Maybe. Not sure how tab usage might have change in 8 years.
Anyway, for pro users, to know if they want a new tab, knowing if something is an external link or one within DS might be helpful. How about indicating external links as such, like Wikipedia does.
![externallink](https://cloud.githubusercontent.com/assets/8145891/26058202/118ca2ca-397d-11e7-8fa9-ceaed19bc27e.PNG)

**Comment by aminalhazwani** [comment]
I tried with this approach but it does not work, am I missing something @bwinton?
```
a {
    // some styles
    &[href*="//"]::after {
      background-image: url('/images/global/open-new-tab.svg');
      background-size: 12px 12px;
      content: "";
      display: inline-block;
      height: 12px;
      margin-left: .5rem;
      width: 12px;
    }
  }
```
I would like to display an icon for all the external links.

**Comment by bwinton** [comment]
Well, it works for me, except for the part where there is no `/images/global/open-new-tab.svg`…  Maybe you could push a branch to show me what the problem you're running into is?

**Comment by aminalhazwani** [comment]
@bwinton you can find the image in `production` branch

**Comment by aminalhazwani** [comment]
@bwinton nevermind, I found the issue, I was styling `a` in `main header` instead of in `main section`, sorry for bothering!
